# Generated by Django 5.2.8 on 2026-02-01 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nazvanie')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='CHPU adres')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categorys',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='nazvanie proekta')),
                ('client', models.CharField(blank=True, max_length=150, verbose_name='klient')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='ssylka')),
                ('description', models.TextField(verbose_name='opisanie')),
                ('video_url', models.URLField(help_text='ssylka na vidos', verbose_name='ssylka na video')),
                ('thumbnail', models.ImageField(help_text='zagruzite skrin', upload_to='project_thumbs/%Y/%m/', verbose_name='oblozhka')),
                ('is_featured', models.BooleanField(default=False, verbose_name='v izbrannoe?')),
                ('is_published', models.BooleanField(default=True, verbose_name='opublikovano?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Chem bolyshe chislo tem vyshe', verbose_name='poryadok')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data sozdaniya')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='vremya izmeneniya')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='video.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'videoproj',
                'verbose_name_plural': 'Videoprojs',
                'ordering': ['-is_featured', '-order', '-created_at'],
            },
        ),
    ]
